"""
rca_agent/agent.py
──────────────────
ReAct-style Root Cause Analysis agent built on Anthropic's tool-use API.

Flow:
  1. Load error log from the observability adapter
  2. Resolve the GitHub repo via RepoResolver (CI/CD → service_repo_map → sub-agent)
  3. Run a ReAct loop (max MAX_REACT_ITERATIONS):
       - Call Claude with 10 tools registered
       - Dispatch tool calls to GitHub helpers / cache / deployment adapter
       - Break on stop_reason == "end_turn" OR finish_rca tool call
  4. Validate & persist the RCA report, then return it
"""

import json
import logging
import uuid
from datetime import datetime, timezone
from typing import Callable

import anthropic

from .cache import read_cache, write_cache, append_rca_history
from .config import settings
from .db import execute
from .github_tools import (
    get_commit_diff,
    get_commits_since,
    get_repo_file,
    list_repo_files,
    search_code_in_repo,
)
from .models import RCAReport
from .report import validate_report
from .repo_resolver import RepoResolver

logger = logging.getLogger(__name__)

# ── System prompt ─────────────────────────────────────────────────────────────

SYSTEM_PROMPT = """You are an expert Site Reliability Engineer performing automated Root Cause Analysis (RCA). You have access to tools to read source code from GitHub, inspect commit diffs, and query deployment history.

PROCESS:
1. Read the error log carefully — note error type, stack trace frames (file + line), service name, environment, and timestamp.
2. Call get_recent_deployments to find what changed recently in the affected service/environment.
3. Fetch the exact files named in the stack trace using get_repo_file (always check read_context_cache first).
4. If there was a recent deployment, call get_commit_diff on the deployed commit SHA to see precisely what changed.
5. Reason about why the error occurred based on the code evidence and diff.
6. When you have sufficient evidence, call finish_rca with a complete, structured report.

RULES:
- Always call read_context_cache before any GitHub API tool. Always call write_context_cache after a successful GitHub fetch.
- Never speculate beyond what you can directly observe in code, diffs, or deployment records.
- Never suggest executing code or making live changes — only provide recommendations.
- finish_rca is the ONLY way to end the analysis loop — you MUST call it.
- Confidence levels: "high" = direct evidence in diff/code; "medium" = strong inference from context; "low" = circumstantial.
- Keep suggested_solutions practical, prioritised (1 = most urgent), and actionable.

RCA REPORT SCHEMA (pass as JSON to finish_rca):
{
  "schema_version": "1.0",
  "rca_id": "<auto-generated uuid4>",
  "error_log_id": "<from the input>",
  "service_name": "<service name>",
  "generated_at": "<ISO 8601 UTC>",
  "incident_summary": {
    "what": "<one sentence>",
    "when": "<ISO timestamp>",
    "environment": "<prod/staging/etc>",
    "severity": "<critical/high/medium/low>",
    "estimated_impact": "<optional>"
  },
  "timeline": [{"timestamp": "<ISO>", "event": "<description>"}],
  "root_cause": {
    "summary": "<clear explanation of what caused the error>",
    "confidence": "high|medium|low",
    "confidence_reason": "<why this confidence level>",
    "code_reference": {
      "file": "<path>",
      "line": <int or null>,
      "function": "<name or null>",
      "repo": "<repo name>",
      "commit_sha": "<sha or null>",
      "github_url": "<url or null>"
    },
    "regression_introduced_by": {
      "commit_sha": "<sha>",
      "commit_message": "<msg>",
      "author": "<name>",
      "deployed_at": "<ISO>"
    } or null
  },
  "contributing_factors": ["<factor>"],
  "evidence": [{"type": "code|diff|deployment|log", "description": "<desc>", "value": "<snippet>"}],
  "impact_assessment": {
    "affected_service": "<name>",
    "affected_environment": "<env>",
    "affected_functionality": "<optional>",
    "inferred_error_rate": "<optional>",
    "duration_estimate": "<optional>"
  },
  "suggested_solutions": [
    {"priority": 1, "effort": "quick-fix|medium|large", "title": "<title>", "description": "<desc>", "code_suggestion": "<optional code snippet>"}
  ],
  "prevention_recommendations": ["<recommendation>"],
  "analysis_metadata": {
    "model": "<model>",
    "react_iterations": <int>,
    "github_files_fetched": ["<path>"],
    "cache_hits": ["<key>"],
    "deployment_record_used": <bool>,
    "repo_discovered_via": "service_repo_map|cicd|sub_agent|cicd+mapping"
  }
}"""

# ── Tool definitions ──────────────────────────────────────────────────────────

TOOLS = [
    {
        "name": "get_repo_file",
        "description": (
            "Fetch the full content of a file from a GitHub repository at a given ref "
            "(branch name or commit SHA). Always call read_context_cache first."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "org": {"type": "string", "description": "GitHub organisation name"},
                "repo": {"type": "string", "description": "Repository name"},
                "path": {"type": "string", "description": "File path within the repo"},
                "ref": {
                    "type": "string",
                    "description": "Branch name or commit SHA (default: main)",
                    "default": "main",
                },
            },
            "required": ["org", "repo", "path"],
        },
    },
    {
        "name": "list_repo_files",
        "description": (
            "List files and directories at a path in a GitHub repo. Useful for exploring "
            "the repo structure before fetching specific files."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "org": {"type": "string"},
                "repo": {"type": "string"},
                "directory": {
                    "type": "string",
                    "description": "Directory path to list (empty string = root)",
                    "default": "",
                },
                "ref": {"type": "string", "default": "main"},
            },
            "required": ["org", "repo"],
        },
    },
    {
        "name": "search_code_in_repo",
        "description": (
            "Search for a string, symbol, or class name within a GitHub repository. "
            "Returns matching file paths and URLs."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "org": {"type": "string"},
                "repo": {"type": "string"},
                "query": {"type": "string", "description": "Search term or symbol"},
            },
            "required": ["org", "repo", "query"],
        },
    },
    {
        "name": "get_commit_diff",
        "description": (
            "Get the full diff (changed files, patches) for a specific commit SHA. "
            "Critical for identifying regressions introduced by recent deployments."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "org": {"type": "string"},
                "repo": {"type": "string"},
                "commit_sha": {"type": "string", "description": "Full or abbreviated commit SHA"},
            },
            "required": ["org", "repo", "commit_sha"],
        },
    },
    {
        "name": "get_commits_since",
        "description": (
            "List commits on a branch since a given timestamp. Useful for finding all "
            "changes that could have contributed to the error."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "org": {"type": "string"},
                "repo": {"type": "string"},
                "branch": {"type": "string"},
                "since": {
                    "type": "string",
                    "description": "ISO 8601 timestamp (e.g. 2026-05-13T00:00:00Z)",
                },
            },
            "required": ["org", "repo", "branch", "since"],
        },
    },
    {
        "name": "get_recent_deployments",
        "description": (
            "Retrieve recent successful deployments for a service/environment pair. "
            "Returns deployment records including commit SHA, branch, deployer, and pipeline URL."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "service_name": {"type": "string"},
                "environment": {"type": "string"},
                "since_hours": {
                    "type": "integer",
                    "description": "How many hours back to look (default: 48)",
                    "default": 48,
                },
                "limit": {"type": "integer", "default": 5},
            },
            "required": ["service_name", "environment"],
        },
    },
    {
        "name": "get_service_metadata",
        "description": "Get metadata about a service from the observability platform.",
        "input_schema": {
            "type": "object",
            "properties": {
                "service_name": {"type": "string"},
            },
            "required": ["service_name"],
        },
    },
    {
        "name": "read_context_cache",
        "description": (
            "Read a previously cached GitHub file or repo tree from the database. "
            "ALWAYS call this before get_repo_file or list_repo_files to avoid redundant API calls."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "service_name": {"type": "string"},
                "cache_key": {
                    "type": "string",
                    "description": "Use 'file:<path>' for files, 'repo_tree' for directory listings",
                },
            },
            "required": ["service_name", "cache_key"],
        },
    },
    {
        "name": "write_context_cache",
        "description": (
            "Persist a GitHub file or repo tree to the cache. "
            "ALWAYS call this after a successful get_repo_file or list_repo_files call."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "service_name": {"type": "string"},
                "cache_key": {"type": "string"},
                "content": {
                    "type": "object",
                    "description": "The content object to cache (file content, tree listing, etc.)",
                },
                "commit_sha": {
                    "type": "string",
                    "description": "Optional commit SHA to associate with the cache entry",
                },
            },
            "required": ["service_name", "cache_key", "content"],
        },
    },
    {
        "name": "finish_rca",
        "description": (
            "Submit the completed RCA report. This MUST be called to end the analysis. "
            "Pass the full report JSON conforming to the RCAReport schema."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "report": {
                    "type": "object",
                    "description": "Full RCA report object conforming to RCAReport schema",
                }
            },
            "required": ["report"],
        },
    },
]


# ── Agent class ───────────────────────────────────────────────────────────────

class RCAAgent:
    def __init__(self, obs_adapter, cicd_adapter):
        self.obs = obs_adapter
        self.cicd = cicd_adapter
        self.client = anthropic.Anthropic(api_key=settings.anthropic_api_key)

    def _emit(self, callback: Callable[[dict], None] | None, event: dict) -> None:
        """Emit a trace event if a callback is registered."""
        if callback is None:
            return
        try:
            event.setdefault("ts", datetime.now(timezone.utc).isoformat())
            callback(event)
        except Exception:
            pass  # trace errors must never crash the agent

    def run(
        self,
        error_log_id: str,
        trace_callback: Callable[[dict], None] | None = None,
    ) -> RCAReport:
        # 1. Load error log
        error_log = self.obs.get_error_log(error_log_id)

        # Emit start event
        self._emit(trace_callback, {
            "type": "start",
            "service": error_log.service_name,
            "error_type": error_log.error_type,
        })

        # 2. Resolve repo
        resolver = RepoResolver(self.cicd)

        # Check if sub-agent will be needed (notification-service has no mapping)
        discovered_via_sub_agent = False
        try:
            from .db import execute_one as _eo
            _mapping = _eo(
                "SELECT service_name FROM service_repo_map WHERE service_name=%s",
                (error_log.service_name,),
            )
            if _mapping is None:
                discovered_via_sub_agent = True
        except Exception:
            pass

        if discovered_via_sub_agent:
            self._emit(trace_callback, {
                "type": "sub_agent",
                "action": f"launching repo discovery for {error_log.service_name}",
            })

        repo_info = resolver.resolve(
            error_log.service_name, error_log.environment, error_log.occurred_at
        )
        logger.info(
            "Resolved repo for %s: %s/%s (via %s)",
            error_log.service_name,
            repo_info["org"],
            repo_info["repo"],
            repo_info["discovered_via"],
        )

        # 3. Build initial context message
        error_context = {
            "error_log_id": error_log_id,
            "service_name": error_log.service_name,
            "environment": error_log.environment,
            "error_type": error_log.error_type,
            "error_message": error_log.error_message,
            "stack_trace": error_log.stack_trace,
            "severity": error_log.severity,
            "occurred_at": error_log.occurred_at.isoformat(),
            "metadata": error_log.metadata,
            "resolved_repo": repo_info,
        }

        messages = [
            {
                "role": "user",
                "content": (
                    "Perform a Root Cause Analysis for the following error. "
                    "Use the available tools to investigate, then call finish_rca.\n\n"
                    f"```json\n{json.dumps(error_context, indent=2, default=str)}\n```"
                ),
            }
        ]

        # 4. ReAct loop
        iterations = 0
        github_files_fetched: list[str] = []
        cache_hits: list[str] = []
        final_report: RCAReport | None = None

        while iterations < settings.max_react_iterations:
            iterations += 1
            logger.debug("ReAct iteration %d", iterations)

            response = self.client.messages.create(
                model=settings.model,
                max_tokens=4096,
                system=SYSTEM_PROMPT,
                tools=TOOLS,
                messages=messages,
            )

            # Append assistant turn
            messages.append({"role": "assistant", "content": response.content})

            # Emit reasoning text blocks (text between tool calls)
            for block in response.content:
                if hasattr(block, "type") and block.type == "text" and block.text.strip():
                    self._emit(trace_callback, {
                        "type": "reasoning",
                        "text": block.text.strip(),
                    })

            if response.stop_reason == "end_turn":
                logger.warning("Agent reached end_turn without calling finish_rca")
                break

            if response.stop_reason != "tool_use":
                logger.warning("Unexpected stop_reason: %s", response.stop_reason)
                break

            # Dispatch tool calls
            tool_results = []
            done = False

            for block in response.content:
                if block.type != "tool_use":
                    continue

                tool_name = block.name
                tool_input = block.input
                result: dict

                # Emit tool_call event (before execution)
                self._emit(trace_callback, {
                    "type": "tool_call",
                    "tool": tool_name,
                    "input": tool_input,
                })

                try:
                    result = self._dispatch(
                        tool_name,
                        tool_input,
                        error_log,
                        repo_info,
                        github_files_fetched,
                        cache_hits,
                        trace_callback=trace_callback,
                    )
                except _FinishRCA as fin:
                    final_report = fin.report
                    done = True
                    tool_results.append(
                        {
                            "type": "tool_result",
                            "tool_use_id": block.id,
                            "content": json.dumps({"status": "rca_submitted"}),
                        }
                    )
                    break
                except Exception as exc:
                    logger.exception("Tool %s raised: %s", tool_name, exc)
                    result = {"error": str(exc)}

                # Emit tool_result event (after execution)
                self._emit(trace_callback, {
                    "type": "tool_result",
                    "tool": tool_name,
                    "summary": self._summarize_result(tool_name, tool_input, result),
                })

                tool_results.append(
                    {
                        "type": "tool_result",
                        "tool_use_id": block.id,
                        "content": json.dumps(result, default=str),
                    }
                )

            messages.append({"role": "user", "content": tool_results})

            if done:
                break

        if final_report is None:
            raise RuntimeError(
                f"RCA agent did not call finish_rca after {iterations} iterations"
            )

        # Update metadata
        final_report.analysis_metadata.react_iterations = iterations
        final_report.analysis_metadata.github_files_fetched = github_files_fetched
        final_report.analysis_metadata.cache_hits = cache_hits
        final_report.analysis_metadata.deployment_record_used = repo_info.get(
            "deployment_record_used", False
        )
        final_report.analysis_metadata.repo_discovered_via = repo_info.get(
            "discovered_via", "unknown"
        )

        # Emit complete event
        self._emit(trace_callback, {
            "type": "complete",
            "confidence": final_report.root_cause.confidence,
            "iterations": iterations,
        })

        # Persist
        self._persist(final_report)
        return final_report

    # ── Tool dispatcher ───────────────────────────────────────────────────────

    def _summarize_result(self, tool_name: str, inp: dict, result: dict) -> str:
        """Generate a short human-readable summary of a tool result."""
        if "error" in result:
            return f"Error from {tool_name}: {result['error']}"
        if tool_name == "get_repo_file":
            path = inp.get("path", "")
            content = result.get("content", "")
            lines = len(content.split("\n")) if isinstance(content, str) else "?"
            return f"Fetched {lines} lines from {path.split('/')[-1]}"
        if tool_name == "list_repo_files":
            items = result.get("files", result.get("tree", []))
            count = len(items) if isinstance(items, list) else "?"
            return f"Listed {count} items in {inp.get('directory', '/') or '/'}"
        if tool_name == "search_code_in_repo":
            items = result.get("results", result.get("items", []))
            count = len(items) if isinstance(items, list) else "?"
            return f"Found {count} results for '{inp.get('query', '')}'"
        if tool_name == "get_commit_diff":
            sha = inp.get("commit_sha", "")[:8]
            files = result.get("files", [])
            additions = sum(f.get("additions", 0) for f in files) if isinstance(files, list) else 0
            deletions = sum(f.get("deletions", 0) for f in files) if isinstance(files, list) else 0
            return f"Commit {sha} diff: {len(files)} files changed (+{additions}/-{deletions})"
        if tool_name == "get_commits_since":
            commits = result.get("commits", [])
            count = len(commits) if isinstance(commits, list) else "?"
            return f"Found {count} commits since {inp.get('since', '')[:10]}"
        if tool_name == "get_recent_deployments":
            deps = result.get("deployments", [])
            return f"Found {len(deps)} recent deployment(s) for {inp.get('service_name', '')}"
        if tool_name == "get_service_metadata":
            return f"Fetched metadata for {inp.get('service_name', '')}"
        if tool_name == "read_context_cache":
            if result.get("cache_hit"):
                return f"Cache hit: {inp.get('cache_key', '')}"
            return f"Cache miss: {inp.get('cache_key', '')}"
        if tool_name == "write_context_cache":
            return f"Cached {inp.get('cache_key', '')} for {inp.get('service_name', '')}"
        return f"{tool_name} completed"

    def _dispatch(
        self,
        name: str,
        inp: dict,
        error_log,
        repo_info: dict,
        github_files_fetched: list[str],
        cache_hits: list[str],
        trace_callback: Callable[[dict], None] | None = None,
    ) -> dict:
        svc = error_log.service_name

        if name == "get_repo_file":
            path = inp["path"]
            result = get_repo_file(
                inp.get("org", repo_info["org"]),
                inp.get("repo", repo_info["repo"]),
                path,
                inp.get("ref", repo_info.get("commit_sha") or "main"),
            )
            if "error" not in result:
                github_files_fetched.append(path)
            return result


        if name == "list_repo_files":
            return list_repo_files(
                inp.get("org", repo_info["org"]),
                inp.get("repo", repo_info["repo"]),
                inp.get("directory", ""),
                inp.get("ref", repo_info.get("commit_sha") or "main"),
            )

        if name == "search_code_in_repo":
            return search_code_in_repo(
                inp.get("org", repo_info["org"]),
                inp.get("repo", repo_info["repo"]),
                inp["query"],
            )

        if name == "get_commit_diff":
            return get_commit_diff(
                inp.get("org", repo_info["org"]),
                inp.get("repo", repo_info["repo"]),
                inp["commit_sha"],
            )

        if name == "get_commits_since":
            return get_commits_since(
                inp.get("org", repo_info["org"]),
                inp.get("repo", repo_info["repo"]),
                inp["branch"],
                inp["since"],
            )

        if name == "get_recent_deployments":
            from datetime import timedelta
            since_hours = inp.get("since_hours", 48)
            since = datetime.now(timezone.utc) - timedelta(hours=since_hours)
            records = self.cicd.get_recent_deployments(
                inp["service_name"],
                inp["environment"],
                since,
                inp.get("limit", 5),
            )
            return {
                "deployments": [
                    {
                        "service_name": r.service_name,
                        "environment": r.environment,
                        "branch": r.branch,
                        "commit_sha": r.commit_sha,
                        "commit_message": r.commit_message,
                        "deployed_at": r.deployed_at.isoformat(),
                        "deployer": r.deployer,
                        "pipeline_id": r.pipeline_id,
                        "pipeline_url": r.pipeline_url,
                        "github_repo": r.github_repo,
                        "status": r.status,
                    }
                    for r in records
                ]
            }

        if name == "get_service_metadata":
            return self.obs.get_service_metadata(inp["service_name"])

        if name == "read_context_cache":
            cached = read_cache(inp["service_name"], inp["cache_key"])
            if cached is not None:
                cache_hits.append(inp["cache_key"])
                self._emit(trace_callback, {"type": "cache_hit", "key": inp["cache_key"]})
                return {"cache_hit": True, "content": cached}
            return {"cache_hit": False}

        if name == "write_context_cache":
            write_cache(
                inp["service_name"],
                inp["cache_key"],
                inp["content"],
                inp.get("commit_sha"),
            )
            return {"status": "cached"}

        if name == "finish_rca":
            inp.setdefault("schema_version", "1.0")
            inp.setdefault("rca_id", str(uuid.uuid4()))
            inp.setdefault("error_log_id", error_log.id)
            inp.setdefault("service_name", error_log.service_name)
            inp.setdefault("generated_at", datetime.now(timezone.utc).isoformat())
            inp.setdefault("analysis_metadata", {})
            inp["analysis_metadata"]["github_files_fetched"] = github_files_fetched
            inp["analysis_metadata"]["cache_hits"] = cache_hits
            inp["analysis_metadata"]["model"] = settings.model
            return {"finish": True, "report_data": inp}

        logger.warning("Unknown tool: %s", name)
        return {"error": f"Unknown tool: {name}"}

    def _persist(self, report: RCAReport, error_log_id: str) -> None:
        """Update error_logs row with completed RCA result."""
        try:
            execute(
                """UPDATE error_logs
                   SET rca_status = 'completed',
                       rca_completed_at = NOW(),
                       rca_result = %s
                   WHERE id = %s""",
                (json.dumps(report.model_dump(mode="json")), error_log_id),
            )
            append_rca_history(report.service_name, {
                "rca_id": report.rca_id,
                "generated_at": report.generated_at,
                "root_cause_summary": report.root_cause.summary,
                "confidence": report.root_cause.confidence,
            })
        except Exception as exc:
            logger.warning("Could not persist RCA report: %s", exc)
